version: "3" 
services:
  
  # php apache
  apache:
    build:
      context: ./php
    container_name: php71-${CONTAINER_PREFIX}
    restart: always
    volumes:
      - "./www:/var/www/html"
      - ./apache2.conf/:/etc/apache2/apache2.conf/    
    ports:
      - ${APP_PORT}:80
    links:
      - mysql
    depends_on:
      - mysql
  
  # data persistence service layer
  mysql:
    image: mysql:5.7.20
    container_name: mysql57-${CONTAINER_PREFIX}
    volumes:
      - "db_data:/var/lib/mysql"
      - "./mysql/initial_data:/docker-entrypoint-initdb.d"
    ports:
      - ${DB_PORT}:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

volumes:
  db_data:
    # external: true
    name: mysql57-vol-${CONTAINER_PREFIX}
